repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--indent", "3", "--output-file", "README.md", "."]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.92.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_tfsec